### ISSUE TITLE
Delete Account Functionality

### ISSUE THREAD

**Issue by Redd77** [BrandonCravener/G-Drive-Sorter#16]
### Expected Behavior
Delete account button deletes Firebase user and corresponding data, and then signs out the user from their google account.
### Actual Behavior
On action, the button does not properly clear the user's data, and fails to sign out the user.
### Steps to reproduce the behavior
1. Sign in to account
2. Navigate to settings tab, and attempt to delete account

**Comment by BrandonCravener** [comment]
Pull request #29 did fix the issue, it was not working due to another bug which is fixed in my next commit.
